### PR TITLE
Upgrade package dependencies

### PR DESCRIPTION
**Pull request by CumpsD**
Upgrade dependencies and make sure the code still works

### CODE REVIEW

**Comment by CumpsD** [comment]
@Aaronontheweb I'm a little bit stuck, if you have some time and could have a look if you find something please?

There are 3 failing tests:
image

The rest are ok:
image

If you debug at `src\Akka.Persistence.Sql\Db\AkkaPersistenceDataConnectionFactory.cs` inside the `HasConversion` funcs (you can temporarly use HasConversionFunc if the breakpoints don't get hit), you will see the DateTime gets converted into Ticks when the test prepares its snapshot data and writes it to MS Sqlite.

```csharp
if (config.ProviderName.ToLower().Contains("sqlite") ||
    config.ProviderName.ToLower().Contains("postgresql"))
{
    builder
        .Member(r => r.Created)
        .HasDataType(DataType.Int64)
        .HasConversion(
            r => r.Ticks,
            r => new DateTime(r));
}
```

However, when it tries to read them, it fails with:
```
Got a message of the expected type <Akka.Persistence.LoadSnapshotResult>. Also expected the predicate to return true but the message {LoadSnapshotResult<toSeqNr: 9223372036854775807, snapshot: >} of type <Akka.Persistence.LoadSnapshotResult> did not match
Expected: True
Actual:   False
   at Akka.TestKit.Xunit2.XunitAssertions.AssertTrue(Boolean condition, String format, Object[] args)
   at Akka.TestKit.TestKitBase.AssertPredicateIsTrueForMessage[T](Predicate`1 isMessage, T m, String hint)
   at Akka.TestKit.TestKitBase.<>c__DisplayClass121_0`1.<ExpectMsgAsync>b__0(T m, IActorRef sender)
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelopeAsync[T](Nullable`1 timeout, Action`2 assert, String hint, CancellationToken cancellationToken, Boolean shouldLog)
   at Akka.TestKit.TestKitBase.InternalExpectMsgAsync[T](Nullable`1 timeout, Action`2 assert, String hint, CancellationToken cancellationToken)
   at Akka.TestKit.TestKitBase.ExpectMsgAsync[T](Predicate`1 isMessage, Nullable`1 timeout, String hint, CancellationToken cancellationToken)
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Predicate`1 isMessage, Nullable`1 timeout, String hint, CancellationToken cancellationToken)
   at Akka.Persistence.TCK.Snapshot.SnapshotStoreSpec.SnapshotStore_should_delete_all_snapshots_matching_upper_sequence_number_and_timestamp_bounds()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

If you debug `src\Akka.Persistence.Sql\Snapshot\ByteArraySnapshotDao.cs` at `SnapshotForMaxSequenceNrAndMaxTimestamp` you will see the values being passed into it are fine, however the `FirstOrDefaultAsync` returns null, even though the row is there:

image

I currently have no idea yet why this is happening. I was trying to find a way to debug the exact query being sent to Sqlite, maybe it doesn't convert the `timestamp` parameter to ticks properly?

**Comment by CumpsD** [comment]
Of course, by typing out my problem I get a step closer to the answer :) I managed to find the query it sends to the database:

```sql
SELECT
	[r].[persistence_id],
	[r].[sequence_number],
	[r].[created],
	[r].[snapshot],
	[r].[manifest],
	[r].[serializer_id]
FROM
	[snapshot] [r]
WHERE
	[r].[persistence_id] = @persistenceId AND [r].[sequence_number] <= @sequenceNr AND
	DateTime([r].[created]) <= DateTime(@timestamp_1)
ORDER BY
	[r].[sequence_number] DESC
LIMIT @take
```

That `DateTime([r].[created]) <= DateTime(@timestamp_1)` is probably the problem, I'll try to figure out why it does that and not simply does the comparison with ticks.

**Comment by Arkatufus** [comment]
@CumpsD I'll look into it

**Comment by CumpsD** [comment]
Just checked with the `dev` branch, the query there is:

```sql
SELECT
	[r].[persistence_id],
	[r].[sequence_number],
	[r].[created],
	[r].[snapshot],
	[r].[manifest],
	[r].[serializer_id]
FROM
	[snapshot] [r]
WHERE
	[r].[persistence_id] = @persistenceId AND [r].[sequence_number] <= @sequenceNr AND
	[r].[created] <= @timestamp_1
ORDER BY
	[r].[sequence_number] DESC
LIMIT @take
```

I'll have a look at linq2db, I'm guessing something changed in the breaking changes from 3->5. I've read all the release notes though, guess I missed something

**Comment by CumpsD** [comment]
Upgrading linq2db to `3.7.0` already changed it to 

```sql
SELECT
	[r].[persistence_id],
	[r].[sequence_number],
	[r].[created],
	[r].[snapshot],
	[r].[manifest],
	[r].[serializer_id]
FROM
	[snapshot] [r]
WHERE
	[r].[persistence_id] = @persistenceId AND [r].[sequence_number] <= @sequenceNr AND
	DateTime([r].[created]) <= DateTime(@timestamp_1)
ORDER BY
	[r].[sequence_number] DESC
LIMIT @take
```

So not even in the breaking changes ;) I will look further as to where it happened

**Comment by CumpsD** [comment]
3.6.0 broke it, https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#release-360

**Comment by CumpsD** [comment]
`3.5.2` is the last version the test succeeds.

`3.6.0` broke it
Release notes: https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#release-360
PR: https://github.com/linq2db/linq2db/pull/3343

I'll have a look at what changed, also asked it in their repo: https://github.com/linq2db/linq2db/pull/3343#issuecomment-1476588402

**Comment by CumpsD** [comment]
Another tidbit of information: https://github.com/linq2db/linq2db/issues/2432
Wrapping with `DateTime()` got added via https://github.com/linq2db/linq2db/pull/478 at https://github.com/linq2db/linq2db/commit/9f6d92c7b13b3299bf22a5018c69d7f11638cb3d#diff-311134ff10546110237f8b2ee7c7fd039c27a57a2fccacf819266612e02363a1R133

**Comment by CumpsD** [comment]
For some reason, the azure checks don't run anymore

**Comment by Aaronontheweb** [comment]
I’ll need to fix that - repo name change broke itSent from my iPhoneOn Mar 21, 2023, at 4:05 AM, David Cumps ***@***.***> wrote:﻿
For some reason, the azure checks don't run anymore

**Comment by CumpsD** [comment]
Just linking some for admin purposes.

* Fixes #162 
* Fixes #161
* Fixes #160
* Fixes #139 
* Fixes #113
* Fixes #112
* Fixes #109 
* Fixes #46
* Fixes #43

**Comment by CumpsD** [comment]
@Arkatufus @Aaronontheweb it's ready for review now, the pipelines are fixed and ran everything succesfully.

Upgrading Linq2db will be in a different PR since it has more impact, and is harder to upgrade (see above)

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Pull request merged**
